### ISSUE TITLE
UH01 - TK009 (#TK014 BORRAR BRANCH DE USUARIOS)

### ISSUE THREAD

**Issue by GERGUSCANO** [GERGUSCANO/ISPC-2023#16]
Cada Integrante debera borrar su Branch para que genere movimiento por parte de cada integrante

**Comment by devluchoc** [comment]
Rama "Lucho" eliminada.

**Comment by DZabala7** [comment]
Rama "Daiana" eliminada.

**Comment by GERGUSCANO** [comment]
termiado
